# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sketch_loadUrlImage' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Sketch'
	pod 'SDWebImage'

  # Pods for Sketch_loadUrlImage

  target 'Sketch_loadUrlImageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Sketch_loadUrlImageUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
