# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sketch_saveAlbum' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Sketch'

  # Pods for Sketch_saveAlbum

  target 'Sketch_saveAlbumTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Sketch_saveAlbumUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
